name: Integración Continua (CI)

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.33
        env:
          MYSQL_ROOT_PASSWORD: 0404
          MYSQL_DATABASE: gestion_turnos
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Descargar el código
        uses: actions/checkout@v3

      - name: Configurar Java 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Inicializar tablas en MySQL
        run: |
          mysql -h 127.0.0.1 -P 3306 -u root -p0404 gestion_turnos < src/main/java/resources/schema.sql
          if [ -f src/main/resources/data.sql ]; then
            mysql -h 127.0.0.1 -P 3306 -u root -p0404 gestion_turnos < src/main/java/resources/data.sql
          fi

      - name: Compilar y Ejecutar Tests
        run: mvn clean test

      - name: Empaquetar el proyecto
        run: mvn package -DskipTests